### ISSUE TITLE
Update and modification to the BC Application Risk Management (ARM) Tool

### ISSUE THREAD

**Issue by bcdevex** [bcgov/nmp-arm#1]
<p>This issue has been auto-generated to facilitate questions about
<a href="https://bcdevexchange.org/opportunities/cwu/opp-update-and-modification-to-the-bc-application-risk-management--arm--tool"> a paid opportunity</a> that has just been posted on the
<a href="https://bcdevexchange.org">BCDevExchange</a>.</p>

<p>To learn more or apply, <a href="https://bcdevexchange.org/opportunities/cwu/opp-update-and-modification-to-the-bc-application-risk-management--arm--tool">visit the opportunity page</a>.
The opportunity closes on <b>Thursday, July 25th, 2019 at 16:00 PDT</b>.</p>

**Comment by WilbertWong** [comment]
Hi and thanks for posting this opportunity! What's the extent and nature of the in-person work required? My developer colleagues are working remotely, but our PM and BA are able to meet and support the project in person. Thank-you.

**Comment by joandrews** [comment]
We would like one or two meetings to go over the proposed changes to the tool (Milestone 2 and 3). Other than that, we expect that the majority of work will be done remotely.

**Comment by WilbertWong** [comment]
Hi @joandrews, have two additional questions. Thanks in advance!

1) Will real data models be available during the project in order to implement some regression tests before an actual migration is performed? Currently, there is no unit test coverage to the missing model libs (mock model?) and that might not be ideal for the migration itself and would add some time to our estimates.

2) Would there be interest in migrating jQuery and Bootstrap to the latest versions while we're at it? It might keep things more responsive. It shouldn't be too difficult but could add to our estimates slightly.

**Comment by joandrews** [comment]
1.	No real data models were provided by the original developer.  We acknowledge the lack of data model and unit tests.
2.	Not as part of Milestone 1, but yes there is interest as part of later Milestones.  Please include the “jQuery and Bootstrap “ estimate as a separate component so that the cost difference is explicit.

**Comment by bcdevex** [comment]
This opportunity has been assigned

**Comment by joandrews** [comment]
Thank you to everyone who submitted a proposal. We had 9 proposals submitted overall.

Based on the evaluation criteria, Colin Spear scored the highest and will be assigned to begin work on this project.

If you submitted a proposal and would like feedback, please contact me at Josh.Andrews@gov.bc.ca

**Comment by bcdevex** [comment]
This opportunity has been un-assigned

**Comment by bcdevex** [comment]
This opportunity has been assigned
